version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1

executors:
  docker-node:
    parameters:
      version:
        default: "lts"
        type: string
    docker:
      - image: cimg/node:<<parameters.version>>

commands:
  install:
    steps:
      - run:
          name: Install
          command: npm install
  test:
    steps:
      - run:
          name: Test
          command: npm test
  test-coverage:
    steps:
      - run:
          name: Test
          command: npm run test:coverage
  release:
    steps:
      - run:
          name: Release
          command: npx semantic-release
  lint:
    steps:
      - run:
          name: Lint
          command: npm run lint

jobs:
  security-scans:
    resource_class: small
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - install
      - prodsec/security_scans:
          mode: auto
          release-branch: master
          open-source-additional-arguments: --exclude=test
          iac-scan: disabled

  test:
    resource_class: medium
    parameters:
      version:
        default: "lts"
        type: string
    executor:
      name: docker-node
      version: <<parameters.version>>
    steps:
      - checkout
      - install
      # This is a workaround because coverage involves a library that does not support node 8 anymore
      - when:
          condition:
            equal: ["8.17.0", << parameters.version >>]
          steps:
            - test
      - when:
          condition:
            not:
              equal: ["8.17.0", << parameters.version >>]
          steps:
            - test-coverage

  release:
    resource_class: small
    executor:
      name: docker-node
    steps:
      - checkout
      - install
      - release

  lint:
    resource_class: small
    executor:
      name: docker-node
    steps:
      - checkout
      - install
      - lint

workflows:

  test:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: os-team-managed-alerts
          filters:
            branches:
              ignore:
                - master

      - security-scans:
          name: Security Scans
          context: open_source-managed
          filters:
            branches:
              ignore:
                - master

      - lint:
          filters:
            branches:
              ignore:
                - master
      - test:
          requires:
            - lint
          matrix:
            parameters:
              version:
                - 18.20.6
                - 20.18.3
                - 22.14.0
          filters:
            branches:
              ignore:
                - master
  release:
    jobs:
      - security-scans:
          name: Security Scans
          context: open_source-managed
          filters:
            branches:
              only:
                - master

      - release:
          context: nodejs-lib-release
          filters:
            branches:
              only:
                - master
